"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/userAuth";
import CheckAuth from "@/components/checkAuth";
import { Provider } from "react-redux";
import store from "@/store/store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <Provider store={store}>
          <body className={inter.className}>
            <CheckAuth>{children}</CheckAuth>
          </body>
        </Provider>
      </AuthProvider>
    </html>
  );
}
